<a href="https://colab.research.google.com/github/Samira1356/new-repo/blob/main/Linear_Regression_with_basic_PyTorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [33]:
import pandas as pd
# ------------------------- 🌱 Data Creation with Region -------------------------
# Create DataFrame with features (including Region) and targets
data = {
    "Region": ["North", "South", "East", "West", "Central"],
    "Humidity": [70, 65, 80, 60, 75],
    "Temperature": [25, 30, 28, 32, 27],
    "Rainfall": [100, 80, 120, 90, 110],
    "Apple_Yield": [150, 140, 170, 135, 165],
    "Orange_Yield": [160, 155, 180, 145, 175]
}

df = pd.DataFrame(data)
print("📊 DataFrame with Region:\n", df)


📊 DataFrame with Region:
     Region  Humidity  Temperature  Rainfall  Apple_Yield  Orange_Yield
0    North        70           25       100          150           160
1    South        65           30        80          140           155
2     East        80           28       120          170           180
3     West        60           32        90          135           145
4  Central        75           27       110          165           175


In Linear Regression moedel, each target variable is estimated to be weighted sum of the inout variables, offset by some constant called bias.

#### Yield_apple = w11 * temp + w12 * rainfall + w13 * humidity + b1
#### Yield_orange = w21 * temp + w22 * rainfall + w23 * humidity + b2

####  Create data frame with features: Humidity, Temprature, Rainfall
####  targets: Apple_Yield and Orange_Yield


In [34]:
import numpy as np
import torch

In [31]:
# represent data into two matrix input as X and target as y
X = df[["Humidity", "Temperature", "Rainfall"]]
y = df[["Apple_Yield", "Orange_Yield"]]

In [32]:
print(type(X))
print(type(y))

<class 'pandas.core.frame.DataFrame'>
<class 'pandas.core.frame.DataFrame'>


In [35]:
# create X and y
X = df[["Humidity", "Temperature", "Rainfall"]]
y = df[["Apple_Yield", "Orange_Yield"]]

In [36]:
print(X)

   Humidity  Temperature  Rainfall
0        70           25       100
1        65           30        80
2        80           28       120
3        60           32        90
4        75           27       110


In [37]:
print(y)

   Apple_Yield  Orange_Yield
0          150           160
1          140           155
2          170           180
3          135           145
4          165           175


In [38]:
# check the type of X and y
print(type(X))
print(type(y))

<class 'pandas.core.frame.DataFrame'>
<class 'pandas.core.frame.DataFrame'>


In [39]:
# check the shape of the X and y
print(X.shape)
print(y.shape)

(5, 3)
(5, 2)


In [40]:
# convert the data to numpy
X = X.values
y = y.values

In [41]:
# print the type
print(type(X))
print(type(y))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [14]:
# convert the data to torch
import torch
X = torch.tensor(X, dtype=torch.float32)
y = torch.tensor(y, dtype=torch.float32)

In [15]:
print(type(X))
print(type(y))

<class 'torch.Tensor'>
<class 'torch.Tensor'>


In [16]:
X

tensor([[ 70.,  25., 100.],
        [ 65.,  30.,  80.],
        [ 80.,  28., 120.],
        [ 60.,  32.,  90.],
        [ 75.,  27., 110.]])

In [17]:
y

tensor([[150., 160.],
        [140., 155.],
        [170., 180.],
        [135., 145.],
        [165., 175.]])

####1.Each element in w is randomly initializing weight connecting a feature to a target.
####2.Bias shifts the preiction curve to better fit the data.
####3.requirres_grad True tells pytorch to track back for these weights during training.

In [42]:
# convert X and y to tensor
X = torch.tensor(X, dtype = torch.float32)
y = torch.tensor(y, dtype = torch.float32)

In [43]:
w = torch.randn(2, 3, requires_grad = True)
b = torch.randn(2, requires_grad = True)

In [44]:
print(w)
print(b)

tensor([[ 1.1640,  0.7965,  0.8543],
        [-1.2539, -0.9568, -1.1002]], requires_grad=True)
tensor([0.7784, 1.5675], requires_grad=True)


In [45]:
# Linear regression model
X @ w.t() + b

tensor([[ 187.6044, -220.1483],
        [ 168.6808, -196.6586],
        [ 218.7204, -257.5622],
        [ 172.9967, -203.3051],
        [ 203.5607, -239.3337]], grad_fn=<AddBackward0>)

In [47]:
y

tensor([[150., 160.],
        [140., 155.],
        [170., 180.],
        [135., 145.],
        [165., 175.]])

Note:
✅ Use x @ w + b when w is (n_features, n_targets). 🔄 Use x @ w.t() + b only if w is (n_targets, n_features).

In [48]:
# now we want to define a function that calculates the linear regression
def model(x):
  return x @ w.t() + b


In [49]:
preds = model(X)
print(preds)

tensor([[ 187.6044, -220.1483],
        [ 168.6808, -196.6586],
        [ 218.7204, -257.5622],
        [ 172.9967, -203.3051],
        [ 203.5607, -239.3337]], grad_fn=<AddBackward0>)


In [50]:
y

tensor([[150., 160.],
        [140., 155.],
        [170., 180.],
        [135., 145.],
        [165., 175.]])

In [51]:
preds -y

tensor([[  37.6044, -380.1483],
        [  28.6808, -351.6586],
        [  48.7204, -437.5622],
        [  37.9967, -348.3051],
        [  38.5607, -414.3337]], grad_fn=<SubBackward0>)

In [56]:
diff = preds - y
torch.sum(diff * diff)/diff.numel()

tensor(76016.7031, grad_fn=<DivBackward0>)

In [57]:
# calculate MSE
def mse(X, y):
  diff = X -y
  return torch.sum(diff * diff)/diff.numel()

In [58]:
# compute loss
loss = mse(preds, y)
print(loss)

tensor(76016.7031, grad_fn=<DivBackward0>)


In [59]:
# compute gradients
loss.backward()

In [60]:
# gradientsfor weights
print(w)
print(w.grad)

tensor([[ 1.1640,  0.7965,  0.8543],
        [-1.2539, -0.9568, -1.1002]], requires_grad=True)
tensor([[  2713.2090,   1084.3477,   3912.5461],
        [-27289.3027, -10927.5957, -39115.8281]])


In [61]:
print(b)
print(b.grad)

tensor([0.7784, 1.5675], requires_grad=True)
tensor([  38.3126, -386.4016])


In [62]:
with torch.no_grad():
  w -= w.grad * 1e-5
  b -= b.grad * 1e-5

In [64]:
print(w)
print(w.grad)

tensor([[ 1.1369,  0.7857,  0.8152],
        [-0.9810, -0.8476, -0.7091]], requires_grad=True)
tensor([[  2713.2090,   1084.3477,   3912.5461],
        [-27289.3027, -10927.5957, -39115.8281]])


In [65]:
print(b)
print(b.grad)

tensor([0.7781, 1.5714], requires_grad=True)
tensor([  38.3126, -386.4016])


In [67]:
loss = mse(preds, y)
print(loss)

tensor(76016.7031, grad_fn=<DivBackward0>)


Update the weights and biases
update the model parameters to reduce the loss in the next iteration

In [68]:
w.grad.zero_()
b.grad.zero_()
print(w.grad)
print(b.grad)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([0., 0.])


In [69]:
print(w)
print(b)

tensor([[ 1.1369,  0.7857,  0.8152],
        [-0.9810, -0.8476, -0.7091]], requires_grad=True)
tensor([0.7781, 1.5714], requires_grad=True)


In [70]:
for i in range(100):
  preds = model(X)
  loss = mse(preds, y)
  loss.backward()
  with torch.no_grad():
    w -= w.grad * 1e-5
    b -= b.grad * 1e-5
    w.grad.zero_()
    b.grad.zero_()

In [71]:
loss = mse(preds, y)
print(loss)

tensor(75.3322, grad_fn=<DivBackward0>)


Repeat with multiple Epoches
wrap above steps training loop to improve over multiple iterations.
iteration is called an epoch. let's train the model for 100 epochs

In [72]:
for i in range(100):
  preds = model(X)
  loss = mse(preds, y)
  loss.backward()
  with torch.no_grad():
    w -= w.grad * 1e-5
    b -= b.grad * 1e-5
    w.grad.zero_()
    b.grad.zero_()

In [73]:
loss = mse(preds, y)
print(loss)

tensor(71.3528, grad_fn=<DivBackward0>)


In [74]:
for i in range(100):
  preds = model(X)
  loss = mse(preds, y)
  loss.backward()
  with torch.no_grad():
    w -= w.grad * 1e-5
    b -= b.grad * 1e-5
    w.grad.zero_()
    b.grad.zero_()

In [75]:
loss = mse(preds, y)
print(loss)

tensor(67.6135, grad_fn=<DivBackward0>)


In [76]:
# take the sqrt of the loss
loss.sqrt()

tensor(8.2227, grad_fn=<SqrtBackward0>)

Ultimately, we want to minimize the loss as much as possible